apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: test-ds
  name: test-ds
spec:
  selector:
    matchLabels:
      app: test-ds
  template:
    metadata:
      labels:
        app: test-ds
    spec:
      containers:
        - image: wbitt/network-multitool
          name: nettoolbox
          securityContext:
            privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: serversvc
spec:
  type: NodePort
  selector:
    app: test-ds
  ports:
    - name: test-ds
      port: 8080
      targetPort: 80
      nodePort: 32000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ds
spec:
  rules:
    - host: test.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: serversvc
                port:
                  number: 80
